"use client";

import { AlertTriangle, ShieldCheck } from "lucide-react";

export default function RiskDisclaimer() {
  return (
    <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 text-sm text-slate-300 shadow-2xl shadow-black/30 backdrop-blur-xl">
      <div className="mb-4 flex items-start gap-3">
        <div className="rounded-2xl bg-amber-400/10 p-2 text-amber-300">
          <AlertTriangle className="h-5 w-5" />
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white">Risk Disclosure & Terms of Use</h2>
          <p className="mt-1 text-slate-400">Apex Quant Terminal is a trading analysis and educational software tool only.</p>
        </div>
      </div>

      <div className="space-y-4 leading-6">
        <DisclosureBlock title="No Financial Advice">
          The Confidence Score, Apex Setup labels, trade levels, safety checklist, and any other outputs generated by Apex Quant Terminal are mathematical interpretations of market data. They are not financial advice, investment advice, trading advice, or buy/sell recommendations.
        </DisclosureBlock>

        <DisclosureBlock title="Capital at Risk">
          Trading financial instruments involves substantial risk. You may lose some or all of your capital, and in certain cases, including margin trading or short selling, you may lose more than your initial investment.
        </DisclosureBlock>

        <DisclosureBlock title="Data Accuracy & Technical Limitations">
          Market data, news sentiment, price levels, volume calculations, execution estimates, and other analytics may contain latency, gaps, inaccuracies, delays, outages, or calculation errors. Apex Quant Terminal does not guarantee real-time accuracy.
        </DisclosureBlock>

        <DisclosureBlock title="User Responsibility">
          The Max Loss Calculator, position sizing estimate, stop-loss level, take-profit level, and break-even point are informational estimates only. You are solely responsible for your own trading decisions, order entry, broker settings, risk limits, and position sizing.
        </DisclosureBlock>
      </div>

      <div className="mt-6 flex items-start gap-3 rounded-2xl border border-cyan-300/10 bg-cyan-300/5 p-4 text-slate-300">
        <ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-cyan-300" />
        <p>By using Apex Quant Terminal, you acknowledge that all trading decisions are made independently and at your own risk.</p>
      </div>
    </section>
  );
}

function DisclosureBlock({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="font-semibold text-white">{title}</h3>
      <p className="mt-1 text-slate-400">{children}</p>
    </div>
  );
}
